name: Go

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/epformat-${{ matrix.goos }}-${{ matrix.goarch }}${{ if eq(matrix.goos, 'windows') }}.exe${{ else }}${{ endif }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: epformat-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/